### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by jasdeep142** [BrianBGrant/DNDCv.CAN#14]
Hi,

I just downloaded the DNDC-Mar5-2024 version. I uploaded all files in the C: directory as recommended. However, the application didn't run as it gave the following error.

![Issue](https://github.com/BrianBGrant/DNDCv.CAN/assets/106292623/26e046bd-283a-48e5-a597-b7955c33377a)

Thanks,
Jasdeep

**Comment by jasdeep142** [comment]
The above comment from me is more an issue from our university system control on certain applications that can installed on C or D drive. The model works perfectly on my personal computer so I am closing this ticket.

**Comment by BrianBGrant** [comment]
Good to hear! Sorry I wasn't able to respond sooner.
