### ISSUE TITLE
Source code is not present in the source control

### ISSUE THREAD

**Issue by rizakazemi** [BrianBGrant/DNDCv.CAN#2]
Hi Brian. I was wondering if you could share the source code of this project? I would like to see if there is a way to incorporate some automation to see effects of changing model variables. 

Thanks!

**Comment by BrianBGrant** [comment]
Hi Riza,

I have a current build of the source code shared privately that I could add
you to. Are you looking to add an automated sensitivity analysis into the
source code? There is the existing Monte Carlo analysis (needs updating to
new parameters/functionality).

Cheers,

Brian

**Comment by rizakazemi** [comment]
Hi Brian,
Thanks, that would be great!

I’m looking to automate the calibration process instead. I am considering something similar to this: https://www.sciencedirect.com/science/article/pii/S0098300498001496

**Comment by BrianBGrant** [comment]
Sorry for the delay. I've added you to a private repository. Feel free to download the source code but please keep it to yourself.

**Comment by rizakazemi** [comment]
Much appreciated!
