### ISSUE TITLE
access to source code

### ISSUE THREAD

**Issue by manipes** [BrianBGrant/DNDCv.CAN#3]
Hi Brian,

Thanks for sharing the updated DNDC with the community. I was wondering if I could get an access to the source code of this project. I am looking for a way to calibrate and simulate the model for the Palm tree which has 25-30 years of life cycle. Few things I would like to explore: time series of Biomass proportion and its C/N ratio, lowering threshold of grain filling to below 0.5 (thanks for including this feature in the latest release as the grain start producing from 5th year for the case of palm).

Thanks,
Manikandan

**Comment by BrianBGrant** [comment]
Hi Manikandan,

I think you might find altering the biomass growth a bit convoluted atm. I am in the midst of simplifying the quadratic implementation of biomass N uptake curves to something more flexible but also easier to manipulate based on cultivar and crop type. I will provide access to the existing framework but I'm hoping to have something improved in the coming months.

Cheers,

Brian

**Comment by manipes** [comment]
Great. Thanks for giving an access. Much Appreciated.

**Comment by BrianBGrant** [comment]
No problem. One thing. Please don't distribute the source code. I know its a honor system request but I would prefer if people asked me directly for access to ensure that "versions" don't get circulated without my knowledge.

**Comment by manipes** [comment]
Sure. I won't distribute the code. Thanks again for sharing.
