### ISSUE TITLE
Executable issue

### ISSUE THREAD

**Issue by jasdeep142** [BrianBGrant/DNDCv.CAN#5]
Dear model developers,
I am following the DNDCv.CAN development for quite sometime and the recent addition of command line is a big step. Congratulations!

The previous version (before command line addition) worked perfectly fine for me. When I downloaded DNDC from this repository last week, and tried to run the model executable file, it did not work because the error reads few missing files in my computer. Those files were ucrtbased.dll, vcruntime140d.dll, msvcp140d.dll, and mfc140d.dll. I added these files, however, the error now reads " The application was unable to start correctly (0xc000007b). Please look at attached snippet.  

Does anyone face this issue? If yes, what is the solution. 

Thank you

![Capture](https://user-images.githubusercontent.com/106292623/170409657-9cf45921-ffeb-48aa-9d90-5639158df14f.PNG)
,

**Comment by BrianBGrant** [comment]
Hi,

Not sure what the issue might have been but I've uploaded a new release of DNDCvCAN for you to download with the release executables along with any possible dll's you should need to run the model. Let me know if you continue to have any problems.

Brian

**Comment by jasdeep142** [comment]
Hello Brian,
Thank you for providing these .dll libraries. The model is now working.
Regards,
Jasdeep
